# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: soaresvictorvso
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: body-measure
service: body-measure

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  profile: default
  memorySize: 256 # optional, in MB, default is 1024
  # stage: dev

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"

custom:
  serverless-offline:
    noPrependStageInUrl: true